# Generated by Django 5.2.7 on 2025-12-02 01:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenesExamenbacteriologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(choices=[('BACILOSCOPIA', 'Baciloscopia'), ('CULTIVO', 'Cultivo'), ('GENEXPERT', 'GeneXpert'), ('XPERTO', 'Xpert MTB/RIF'), ('LAM', 'LAM (Urinario)'), ('PPD', 'PPD (Tuberculina)'), ('RADIOGRAFIA', 'Radiografía de Tórax'), ('TAMIZAJE', 'Tamizaje Molecular')], max_length=100, verbose_name='Tipo de Examen')),
                ('tipo_muestra', models.CharField(choices=[('ESPUTO', 'Esputo'), ('ESPUTO_INDUCIDO', 'Esputo Inducido'), ('LAVADO_GASTRICO', 'Lavado Gástrico'), ('ASPIRADO', 'Aspirado Bronquial'), ('BIOPSIA', 'Biopsia'), ('SANGRE', 'Sangre'), ('ORINA', 'Orina'), ('LIQUIDO_CEFALORRAQUIDEO', 'Líquido Cefalorraquídeo'), ('LIQUIDO_PLEURAL', 'Líquido Pleural'), ('OTRO', 'Otro')], max_length=100, verbose_name='Tipo de Muestra')),
                ('otro_tipo_muestra', models.CharField(blank=True, max_length=100, null=True, verbose_name='Especificar otro tipo de muestra')),
                ('fecha_solicitud', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Solicitud')),
                ('fecha_toma_muestra', models.DateField(verbose_name='Fecha de Toma de Muestra')),
                ('fecha_ingreso_laboratorio', models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso Laboratorio')),
                ('fecha_resultado', models.DateField(blank=True, null=True, verbose_name='Fecha de Resultado')),
                ('resultado', models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo'), ('INDETERMINADO', 'Indeterminado'), ('CONTAMINADO', 'Contaminado'), ('PENDIENTE', 'Pendiente'), ('NO_APLICA', 'No Aplica')], default='PENDIENTE', max_length=100, verbose_name='Resultado')),
                ('resultado_cuantitativo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Resultado Cuantitativo')),
                ('resultado_cualitativo', models.TextField(blank=True, null=True, verbose_name='Resultado Cualitativo')),
                ('sensibilidad', models.CharField(blank=True, choices=[('SENSIBLE', 'Sensible'), ('RESISTENTE', 'Resistente'), ('MONO_RESISTENTE', 'Mono-Resistente'), ('POLI_RESISTENTE', 'Poli-Resistente'), ('ULTRA_RESISTENTE', 'Ultra-Resistente'), ('MDR', 'MDR (Multidrogorresistente)'), ('XDR', 'XDR (Extensamente resistente)'), ('PENDIENTE', 'Pendiente'), ('NO_APLICA', 'No Aplica')], max_length=100, null=True, verbose_name='Sensibilidad')),
                ('resistencia_isoniazida', models.BooleanField(default=False, verbose_name='Resistente a Isoniazida')),
                ('resistencia_rifampicina', models.BooleanField(default=False, verbose_name='Resistente a Rifampicina')),
                ('resistencia_pirazinamida', models.BooleanField(default=False, verbose_name='Resistente a Pirazinamida')),
                ('resistencia_etambutol', models.BooleanField(default=False, verbose_name='Resistente a Etambutol')),
                ('resistencia_estreptomicina', models.BooleanField(default=False, verbose_name='Resistente a Estreptomicina')),
                ('resistencia_fluoroquinolonas', models.BooleanField(default=False, verbose_name='Resistente a Fluoroquinolonas')),
                ('observaciones_muestra', models.TextField(blank=True, null=True, verbose_name='Observaciones de la Muestra')),
                ('observaciones_resultado', models.TextField(blank=True, null=True, verbose_name='Observaciones del Resultado')),
                ('estado_examen', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('MUESTRA_TOMADA', 'Muestra Tomada'), ('ENVIADO_LABORATORIO', 'Enviado a Laboratorio'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=50, verbose_name='Estado del Examen')),
                ('prioridad', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente'), ('EMERGENCIA', 'Emergencia')], default='NORMAL', max_length=20, verbose_name='Prioridad')),
                ('laboratorio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Laboratorio de Referencia')),
                ('numero_muestra_lab', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Muestra Laboratorio')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_bacteriologicos', to='pacientes.pacientespaciente')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_registrados', to=settings.AUTH_USER_MODEL)),
                ('usuario_toma_muestra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes_toma_muestra', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que tomó la muestra')),
            ],
            options={
                'verbose_name': 'Examen Bacteriológico',
                'verbose_name_plural': 'Exámenes Bacteriológicos',
                'db_table': 'examenes_examenbacteriologico',
                'ordering': ['-fecha_toma_muestra', '-fecha_registro'],
                'indexes': [models.Index(fields=['paciente', 'fecha_toma_muestra'], name='examenes_ex_pacient_b5185f_idx'), models.Index(fields=['tipo_examen', 'resultado'], name='examenes_ex_tipo_ex_7f0aa1_idx'), models.Index(fields=['estado_examen'], name='examenes_ex_estado__e5b159_idx')],
            },
        ),
    ]
