# Generated by Django 5.2.7 on 2025-11-30 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examenradiologico',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='examenradiologico',
            name='usuario_registro',
        ),
        migrations.DeleteModel(
            name='ExamenPPD',
        ),
        migrations.DeleteModel(
            name='ExamenRadiologico',
        ),
    ]
