# Generated by Django 5.2.7 on 2025-12-02 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(default='Centro de Salud', max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Establecimientos',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VENCIMIENTO', 'Vencimiento'), ('RESULTADO', 'Resultado'), ('SEGUIMIENTO', 'Seguimiento'), ('EPIDEMIOLOGICA', 'Alerta Epidemiológica'), ('CALIDAD', 'Calidad de Datos')], max_length=20)),
                ('nivel', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('datos_relacionados', models.JSONField(blank=True, default=dict)),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.establecimiento')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='IndicadoresPrevencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('contactos_elegibles_qp', models.IntegerField(default=0)),
                ('contactos_iniciados_qp', models.IntegerField(default=0)),
                ('contactos_completados_qp', models.IntegerField(default=0)),
                ('recien_nacidos', models.IntegerField(default=0)),
                ('recien_nacidos_vacunados', models.IntegerField(default=0)),
                ('tiempo_promedio_inicio_qp', models.IntegerField(default=0)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.establecimiento')),
            ],
            options={
                'verbose_name': 'Indicador de Prevención',
                'verbose_name_plural': 'Indicadores de Prevención',
            },
        ),
        migrations.CreateModel(
            name='ReportePersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('columnas_visibles', models.JSONField(blank=True, default=list)),
                ('filtros', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('compartido', models.BooleanField(default=False)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuarios_compartidos', models.ManyToManyField(blank=True, related_name='reportes_compartidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Personalizado',
                'verbose_name_plural': 'Reportes Personalizados',
            },
        ),
        migrations.CreateModel(
            name='IndicadoresCohorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('trimestre', models.CharField(choices=[('Q1', 'Primer Trimestre'), ('Q2', 'Segundo Trimestre'), ('Q3', 'Tercer Trimestre'), ('Q4', 'Cuarto Trimestre')], max_length=2)),
                ('casos_nuevos', models.IntegerField(default=0)),
                ('casos_retratamiento', models.IntegerField(default=0)),
                ('curados', models.IntegerField(default=0)),
                ('abandonos', models.IntegerField(default=0)),
                ('fallecidos', models.IntegerField(default=0)),
                ('fracasos', models.IntegerField(default=0)),
                ('trasladados', models.IntegerField(default=0)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.establecimiento')),
            ],
            options={
                'verbose_name': 'Indicador de Cohorte',
                'verbose_name_plural': 'Indicadores de Cohorte',
                'unique_together': {('año', 'trimestre', 'establecimiento')},
            },
        ),
        migrations.CreateModel(
            name='IndicadoresOperacionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('sintomaticos_respiratorios', models.IntegerField(default=0)),
                ('baciloscopias_realizadas', models.IntegerField(default=0)),
                ('casos_tb_encontrados', models.IntegerField(default=0)),
                ('contactos_identificados', models.IntegerField(default=0)),
                ('contactos_estudiados', models.IntegerField(default=0)),
                ('pacientes_taes', models.IntegerField(default=0)),
                ('pacientes_adherentes', models.IntegerField(default=0)),
                ('tiempo_promedio_diagnostico', models.IntegerField(default=0)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.establecimiento')),
            ],
            options={
                'verbose_name': 'Indicador Operacional',
                'verbose_name_plural': 'Indicadores Operacionales',
                'unique_together': {('establecimiento', 'periodo')},
            },
        ),
    ]
