# Generated by Django 5.2.7 on 2025-12-02 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactos', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevencionQuimioprofilaxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_paciente', models.CharField(choices=[('paciente', 'Paciente'), ('contacto', 'Contacto')], max_length=10)),
                ('medicamento', models.CharField(choices=[('isoniacida', 'Isoniacida (H)'), ('rifampicina', 'Rifampicina (R)'), ('combinado', 'Combinado HR')], max_length=20)),
                ('dosis', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino_prevista', models.DateField()),
                ('fecha_termino_real', models.DateField(blank=True, null=True)),
                ('esquema', models.CharField(max_length=50)),
                ('adherencia_porcentaje', models.IntegerField(default=0)),
                ('efectos_adversos', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('completado', 'Completado'), ('suspendido', 'Suspendido'), ('abandonado', 'Abandonado')], default='pendiente', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contactos.contactoscontacto')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.pacientespaciente')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Quimioprofilaxis',
                'db_table': 'prevencion_quimioprofilaxis',
            },
        ),
        migrations.CreateModel(
            name='PrevencionVacunacionBCG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vacunacion', models.DateField()),
                ('lote', models.CharField(max_length=50)),
                ('establecimiento', models.CharField(max_length=200)),
                ('reaccion', models.CharField(choices=[('ninguna', 'Ninguna'), ('leve', 'Leve'), ('moderada', 'Moderada'), ('severa', 'Severa')], default='ninguna', max_length=10)),
                ('observaciones_reaccion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.pacientespaciente')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vacunaciones BCG',
                'db_table': 'prevencion_vacunacion_bcg',
            },
        ),
        migrations.CreateModel(
            name='PrevencionSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_seguimiento', models.CharField(choices=[('quimioprofilaxis', 'Quimioprofilaxis'), ('vacunacion', 'Vacunación')], max_length=20)),
                ('fecha_seguimiento', models.DateField()),
                ('resultado', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('proximo_control', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('quimioprofilaxis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prevencion.prevencionquimioprofilaxis')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vacunacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prevencion.prevencionvacunacionbcg')),
            ],
            options={
                'verbose_name_plural': 'Seguimientos Prevención',
                'db_table': 'prevencion_seguimiento',
            },
        ),
    ]
