# Generated by Django 5.2.7 on 2025-12-02 01:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examenes', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratorioRedLaboratorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('I', 'Tipo I - Básico'), ('II', 'Tipo II - Intermedio'), ('III', 'Tipo III - Avanzado')], max_length=3)),
                ('direccion', models.CharField(max_length=300)),
                ('comuna', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Red de Laboratorios',
                'db_table': 'laboratorio_red_laboratorios',
            },
        ),
        migrations.CreateModel(
            name='LaboratorioControlCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_control', models.DateField()),
                ('tipo_control', models.CharField(choices=[('peec', 'PEEC - Programa Externo'), ('interno', 'Control Interno'), ('interlaboratorio', 'Interlaboratorio')], max_length=20)),
                ('resultado', models.CharField(choices=[('satisfactorio', 'Satisfactorio'), ('insatisfactorio', 'Insatisfactorio'), ('pendiente', 'Pendiente')], default='pendiente', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.laboratorioredlaboratorios')),
            ],
            options={
                'verbose_name_plural': 'Controles de Calidad',
                'db_table': 'laboratorio_control_calidad',
            },
        ),
        migrations.CreateModel(
            name='LaboratorioTarjetero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_deteccion', models.DateField()),
                ('tipo_muestra', models.CharField(choices=[('esputo', 'Esputo'), ('aspirado', 'Aspirado Gastrico'), ('lavado', 'Lavado Bronquial'), ('otros', 'Otros')], max_length=20)),
                ('resultado', models.CharField(max_length=100)),
                ('fecha_notificacion', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenes.examenesexamenbacteriologico')),
                ('laboratorio_referencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laboratorio.laboratorioredlaboratorios')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.pacientespaciente')),
                ('usuario_notificador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tarjetero de Positivos',
                'db_table': 'laboratorio_tarjetero',
            },
        ),
        migrations.CreateModel(
            name='LaboratorioIndicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=7)),
                ('muestras_recibidas', models.IntegerField(default=0)),
                ('muestras_procesadas', models.IntegerField(default=0)),
                ('positivos', models.IntegerField(default=0)),
                ('contaminacion_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tiempo_respuesta_promedio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.laboratorioredlaboratorios')),
            ],
            options={
                'verbose_name_plural': 'Indicadores Laboratorio',
                'db_table': 'laboratorio_indicadores',
                'unique_together': {('laboratorio', 'periodo')},
            },
        ),
    ]
