# Generated by Django 5.2.7 on 2025-10-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PacientesPaciente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('domicilio', models.TextField()),
                ('comuna', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('establecimiento_salud', models.CharField(max_length=100)),
                ('fecha_diagnostico', models.DateField(blank=True, null=True)),
                ('tipo_tbc', models.CharField(choices=[('pulmonar', 'TBC Pulmonar'), ('extrapulmonar', 'TBC Extrapulmonar'), ('mixta', 'TBC Mixta')], max_length=50)),
                ('baciloscopia_inicial', models.CharField(blank=True, max_length=50, null=True)),
                ('cultivo_inicial', models.CharField(blank=True, max_length=50, null=True)),
                ('poblacion_prioritaria', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo en tratamiento'), ('suspendido', 'Tratamiento suspendido'), ('egresado', 'Egresado'), ('abandono', 'Abandono'), ('fallecido', 'Fallecido')], default='activo', max_length=50)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pacientes_paciente',
                'managed': False,
            },
        ),
    ]
