# Generated by Django 5.2.7 on 2025-11-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientespaciente',
            name='alergias',
            field=models.TextField(blank=True, help_text='Alergias conocidas del paciente', null=True),
        ),
        migrations.AddField(
            model_name='pacientespaciente',
            name='enfermedades_preexistentes',
            field=models.TextField(blank=True, help_text='Enfermedades preexistentes del paciente', null=True),
        ),
    ]
