# Generated by Django 5.2.7 on 2025-11-30 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_pacientespaciente_alergias_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacientespaciente',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
    ]
