# Generated by Django 5.2.7 on 2025-12-02 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('esquema', models.CharField(choices=[('HRZE', 'HRZE - Isoniazida, Rifampicina, Pirazinamida, Etambutol'), ('HRE', 'HRE - Isoniazida, Rifampicina, Etambutol'), ('HR', 'HR - Isoniazida, Rifampicina'), ('Personalizado', 'Esquema Personalizado')], max_length=50, verbose_name='Esquema Terapéutico')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_termino_estimada', models.DateField(verbose_name='Fecha Término Estimada')),
                ('fecha_termino_real', models.DateField(blank=True, null=True, verbose_name='Fecha Término Real')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('resultado_final', models.CharField(blank=True, choices=[('Curación', 'Curación'), ('Tratamiento Completo', 'Tratamiento Completo'), ('Fallecimiento', 'Fallecimiento'), ('Fracaso', 'Fracaso'), ('Abandono', 'Abandono'), ('Transferencia', 'Transferencia'), ('En Tratamiento', 'En Tratamiento')], max_length=50, null=True, verbose_name='Resultado Final')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='pacientes.pacientespaciente', verbose_name='Paciente')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratamientos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'db_table': 'tratamientos_tratamiento',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EsquemaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(choices=[('Isoniazida (H)', 'Isoniazida (H)'), ('Rifampicina (R)', 'Rifampicina (R)'), ('Pirazinamida (Z)', 'Pirazinamida (Z)'), ('Etambutol (E)', 'Etambutol (E)'), ('Estreptomicina (S)', 'Estreptomicina (S)'), ('Levofloxacino', 'Levofloxacino'), ('Moxifloxacino', 'Moxifloxacino'), ('Amikacina', 'Amikacina'), ('Kanamicina', 'Kanamicina'), ('Capreomicina', 'Capreomicina')], max_length=100)),
                ('dosis_mg', models.IntegerField(verbose_name='Dosis (mg)')),
                ('frecuencia', models.CharField(choices=[('Diaria', 'Diaria'), ('3 veces por semana', '3 veces por semana'), ('2 veces por semana', '2 veces por semana'), ('Semanal', 'Semanal')], max_length=50)),
                ('fase', models.CharField(choices=[('Fase Intensiva', 'Fase Intensiva'), ('Fase Continuación', 'Fase Continuación'), ('Fase Completa', 'Fase Completa')], max_length=50)),
                ('duracion_semanas', models.IntegerField(verbose_name='Duración (semanas)')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esquemas_medicamento', to='tratamientos.tratamiento')),
            ],
            options={
                'verbose_name': 'Esquema de Medicamento',
                'verbose_name_plural': 'Esquemas de Medicamento',
                'db_table': 'tratamientos_esquemamedicamento',
            },
        ),
        migrations.CreateModel(
            name='DosisAdministrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_dosis', models.DateField(verbose_name='Fecha de Dosis')),
                ('administrada', models.BooleanField(default=False, verbose_name='¿Administrada?')),
                ('hora_administracion', models.TimeField(blank=True, null=True, verbose_name='Hora de Administración')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario_administracion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dosis_administradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que administró')),
                ('esquema_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosis_administradas', to='tratamientos.esquemamedicamento')),
            ],
            options={
                'verbose_name': 'Dosis Administrada',
                'verbose_name_plural': 'Dosis Administradas',
                'db_table': 'tratamientos_dosisadministrada',
                'unique_together': {('esquema_medicamento', 'fecha_dosis')},
            },
        ),
    ]
