# Generated by Django 5.2.7 on 2025-11-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
