# Generated by Django 5.2.7 on 2025-11-13 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosUsuario',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='usuariosusuario', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rut', models.CharField(max_length=15, unique=True)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('enfermera', 'Enfermera'), ('medico', 'Médico'), ('tecnologo', 'Tecnologo Médico'), ('paramedico', 'Técnico Paramédico')], default='enfermera', max_length=50)),
                ('establecimiento', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuario del Sistema',
                'verbose_name_plural': 'Usuarios del Sistema',
                'db_table': 'usuarios_usuario',
            },
        ),
    ]
