# Generated by Django 5.2.7 on 2025-10-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactosContacto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut_contacto', models.CharField(max_length=12)),
                ('nombre_contacto', models.CharField(max_length=200)),
                ('parentesco', models.CharField(max_length=100)),
                ('tipo_contacto', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('estado_estudio', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'contactos_contacto',
                'managed': False,
            },
        ),
    ]
