# Generated by Django 5.2.7 on 2025-11-13 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactosContacto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut_contacto', models.CharField(max_length=12)),
                ('nombre_contacto', models.CharField(max_length=200)),
                ('parentesco', models.CharField(choices=[('', 'Seleccione parentesco'), ('esposo_esposa', 'Esposo/a'), ('hijo_hija', 'Hijo/a'), ('padre_madre', 'Padre/Madre'), ('hermano_hermana', 'Hermano/a'), ('abuelo_abuela', 'Abuelo/a'), ('nieto_nieta', 'Nieto/a'), ('tio_tia', 'Tío/a'), ('sobrino_sobrina', 'Sobrino/a'), ('primo_prima', 'Primo/a'), ('cuñado_cuñada', 'Cuñado/a'), ('suegro_suegra', 'Suegro/a'), ('yerno_nuera', 'Yerno/Nuera'), ('otro_familiar', 'Otro Familiar'), ('no_familiar', 'No Familiar'), ('vecino', 'Vecino'), ('compañero_trabajo', 'Compañero de Trabajo'), ('compañero_estudio', 'Compañero de Estudio'), ('otro', 'Otro')], default='', max_length=100)),
                ('tipo_contacto', models.CharField(choices=[('', 'Seleccione tipo de contacto'), ('intradomiciliario', 'Intradomiciliario'), ('extradomiciliario', 'Extradomiciliario'), ('laboral', 'Laboral'), ('escolar', 'Escolar'), ('social', 'Social'), ('otro', 'Otro')], default='', max_length=100)),
                ('fecha_registro', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('estado_estudio', models.CharField(choices=[('', 'Seleccione estado'), ('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('rechazado', 'Rechazado'), ('no_aplica', 'No Aplica')], default='pendiente', max_length=100)),
                ('paciente_indice', models.ForeignKey(db_column='paciente_indice_id', on_delete=django.db.models.deletion.CASCADE, to='pacientes.pacientespaciente')),
            ],
            options={
                'db_table': 'contactos_contacto',
            },
        ),
    ]
